multi-threading: multi-threading.out
	gcc -o multi-threading.out ./main.c -pthread
	./multi-threading.out

multi-threading.out: main.c
	gcc -o multi-threading.out ./main.c -pthread

clean:
	rm -f *.out
